<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>1937MapEditor</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MapEditor.Core/MapEditor.Core.csproj" />
  </ItemGroup>
</Project>
